### ISSUE TITLE
environment variable `VERGEN_BUILD_DATE` not defined

### ISSUE THREAD

**Issue by williamdes** [rustyhorde/vergen#137]
I switched to `VERGEN_BUILD_TIMESTAMP` 

See: https://docs.rs/vergen/latest/vergen/#environment-variables

```toml
[build-dependencies]
anyhow = "1.0.63"
vergen = { version = "7.4.2", default-features = false, features = ["build", "git"] }
```

Also, could we not need `anyhow` ?
